-- This module is the root of the GeneralizedGeometricLanglandsCanonicalLaneLean Lean proof package.
import GeneralizedGeometricLanglandsCanonicalLaneLean.Basic
import GeneralizedGeometricLanglandsCanonicalLaneLean.SourcePackage
import GeneralizedGeometricLanglandsCanonicalLaneLean.SourceDependencies
import GeneralizedGeometricLanglandsCanonicalLaneLean.Formalization
import GeneralizedGeometricLanglandsCanonicalLaneLean.ReviewerBridge
import GeneralizedGeometricLanglandsCanonicalLaneLean.TheoremStatement
import GeneralizedGeometricLanglandsCanonicalLaneLean.MathlibObjects
import GeneralizedGeometricLanglandsCanonicalLaneLean.AdmissibleClass
import GeneralizedGeometricLanglandsCanonicalLaneLean.Projection
import GeneralizedGeometricLanglandsCanonicalLaneLean.BridgeLemmas
import GeneralizedGeometricLanglandsCanonicalLaneLean.GateLemmas
import GeneralizedGeometricLanglandsCanonicalLaneLean.FinalTheorem
import GeneralizedGeometricLanglandsCanonicalLaneLean.MathlibStatement
